# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-05 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suicide_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reason',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
