# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-26 00:21
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentarticle',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='edit', template='wagtail_blocks/paragraph.html')), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(icon='image', template='wagtail_blocks/image.html')), ('full_width_image', wagtail.wagtailimages.blocks.ImageChooserBlock(icon='image', template='wagtail_blocks/full_width_image.html'))), default=''),
        ),
    ]
